import dotenv from 'dotenv';
dotenv.config();

//Hugging face client...
import { HfInference } from '@huggingface/inference';
const client = new HfInference(process.env.HUGGINGFACE_API_KEY);


const getAiResponse = async (prompt) => {
  try {
    // const response = await fetch(HUGGINGFACE_BASE_URL, {

    //   method: 'POST',
    //   headers: {
    //     'Authorization': `Bearer ${HUGGINGFACE_API_KEY}`,
    //     'Content-Type': 'application/json',
    //   },
    //   body: JSON.stringify({
    //     inputs: prompt,
    //   }),
    // });

    const response = await client.textGeneration({
      model: "gpt-3.5-turbo",  // Or any other compatible model
      inputs: prompt,  // Your prompt for the model
      max_tokens: 500,  // Maximum number of tokens (words/characters) for the response
    });

    const generatedText = response.generated_text;  // Extracting the generated text from the response

    if (!generatedText) {
      throw new Error('No response generated by the model.');
    }

    return generatedText;
  } 
  catch (error) {
    console.error("Error communicating with Hugging Face API:", error);
    throw error;
  }
};

export default getAiResponse;